### ISSUE TITLE
Error Handler

### ISSUE THREAD

**Issue by AllKinds** [meateam/seal#16]
Read _Valeri Karpov's_ [Guide to Express Error Handling](http://thecodebarbarian.com/80-20-guide-to-express-error-handling) and apply it in our project.

**Comment by Shahar-Y** [comment]
Read it. not sure if the implementation is what we want to use.
also read: 
* [Making exceptions type safe in Typescript](https://medium.com/@dhruvrajvanshi/making-exceptions-type-safe-in-typescript-c4d200ee78e9) : the implementation suggested there is nice but seems too clumsy

**Comment by Shahar-Y** [comment]
Update: Started reading about [Mongoose Error Handling](http://thecodebarbarian.com/mongoose-error-handling) by [The Code Barbarian](http://thecodebarbarian.com). Trying to implement it and integrate it with ServerError.

**Comment by Shahar-Y** [comment]
Done for now with #22

**Comment by Shahar-Y** [comment]
Reopened. 
Decided on using Karpov's error handling method.
